### ISSUE TITLE
Black Screen?

### ISSUE THREAD

**Issue by knightcrawler25** [SerhiiY-94/Ray#1]
Hi,

I am trying to compile and run your code and using the test2 branch from
https://bitbucket.org/Apfel1994/raydemo/src/9939b7473b9ecf379496208dbe14e2edf1d2ff84/?at=test2
and unzipped libs.zip into the src/libs folder but kept the assets folder as is since I'm trying to render the staircase.json file but when I run DemoApp I only get a black screen in the viewer with the following in the console:

1 file(s) copied.
My CPU is a GenuntelineI

Device info:
        Vendor          : Unknown
        Renderer        : Software
Capabilities:
        CPU Model               : Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz
        Num CPUs                : 4
        Physical memory : 7.887196 GB
        Max uniforms    : 128
        Bones per pass  : 64

Ray: Creating Ref renderer 400x500
2018-12-17 15:55:07.000 | 6334  2086    6861    1
2018-12-17 15:55:07.000 | 6549  3194    7588    1
2018-12-17 15:55:07.000 | 6696  3607    6816    2

Right now I haven't dug into the project, but is there something else I'm missing?

Thanks,
Asif

**Comment by SerhiiY-94** [comment]
Hi Asif,

I reorganized everything. Now master branch includes staircase and coffee scenes. All resources are included in repository, so no scripts needed. Specific scenes can be ran through .bat files.
Also you can download windows binaries from here https://ci.appveyor.com/project/SerhiiY/raydemo/builds/21066118/artifacts

I still have some problems on my nvidia card though. But CPU version should work 100%.

Kind Regards,
Serhii

**Comment by knightcrawler25** [comment]
Hi Serhii,

It all neatly organized and works perfectly now :) 👍  Thanks a lot. Also, thanks for sharing your code in the first place. Its quite useful as a way to learn for hobbyists like me :)

Regards,
Asif
